import { Router } from "express";
import {
  me,
  list,
  getById,
  updateMe,
  changePassword,
  deleteAccount,
  exportData,
  listUserContacts,
  updateEmail,
  updatePhone,
  requestContactVerificationHandler,
  verifyContactHandler,
  removeContactHandler,
  adminChangeStatus,
  adminCreateUser,
  getMetrics,
  getPrivacy,
  updatePrivacy,
  getPreferences,
  updatePreferences,
} from "./users.controller.js";
import { requireAccessToken } from "../auth/auth.middleware.js";
import { requireRole } from "../common/rbac.middleware.js";
import { rateLimit } from "../common/rateLimiter.js";
import { usersAvatarRouter } from "./users.avatar.routes.js";
import { usersBodyProgressRouter } from "./users.body-progress.routes.js";
import { asyncHandler } from "../../utils/async-handler.js";
import {
  followUserHandler,
  listFollowersHandler,
  listFollowingHandler,
  unfollowUserHandler,
} from "../feed/feed.controller.js";

export const usersRouter = Router();

usersRouter.use(usersAvatarRouter);
usersRouter.use(usersBodyProgressRouter);

usersRouter.get("/me", rateLimit("user_me"), requireAccessToken, asyncHandler(me));
usersRouter.patch(
  "/me",
  rateLimit("user_update"),
  requireAccessToken,
  asyncHandler(updateMe),
);
usersRouter.post(
  "/change-password",
  rateLimit("user_pw"),
  requireAccessToken,
  asyncHandler(changePassword),
);
usersRouter.delete(
  "/me",
  rateLimit("user_delete"),
  requireAccessToken,
  asyncHandler(deleteAccount),
);
usersRouter.get(
  "/me/contacts",
  rateLimit("user_contacts_get"),
  requireAccessToken,
  asyncHandler(listUserContacts),
);
usersRouter.put(
  "/me/contacts/email",
  rateLimit("user_contacts_email"),
  requireAccessToken,
  asyncHandler(updateEmail),
);
usersRouter.put(
  "/me/contacts/phone",
  rateLimit("user_contacts_phone"),
  requireAccessToken,
  asyncHandler(updatePhone),
);
usersRouter.post(
  "/me/contacts/:contactId/request-verification",
  rateLimit("user_contacts_verify_request"),
  requireAccessToken,
  asyncHandler(requestContactVerificationHandler),
);
usersRouter.post(
  "/me/contacts/:contactId/verify",
  rateLimit("user_contacts_verify"),
  requireAccessToken,
  asyncHandler(verifyContactHandler),
);
usersRouter.delete(
  "/me/contacts/:contactId",
  rateLimit("user_contacts_delete"),
  requireAccessToken,
  asyncHandler(removeContactHandler),
);
usersRouter.post(
  "/",
  rateLimit("user_create"),
  requireAccessToken,
  requireRole("admin"),
  asyncHandler(adminCreateUser),
);
usersRouter.get(
  "/",
  rateLimit("user_list"),
  requireAccessToken,
  requireRole("admin"),
  asyncHandler(list),
);
usersRouter.get(
  "/me/export",
  requireAccessToken,
  rateLimit("user_export"),
  asyncHandler(exportData),
);
usersRouter.get(
  "/me/preferences",
  rateLimit("user_preferences_get"),
  requireAccessToken,
  asyncHandler(getPreferences),
);
usersRouter.patch(
  "/me/preferences",
  rateLimit("user_preferences_update"),
  requireAccessToken,
  asyncHandler(updatePreferences),
);
usersRouter.get(
  "/me/privacy",
  rateLimit("user_privacy_get"),
  requireAccessToken,
  asyncHandler(getPrivacy),
);
usersRouter.patch(
  "/me/privacy",
  rateLimit("user_privacy_update"),
  requireAccessToken,
  asyncHandler(updatePrivacy),
);
usersRouter.patch(
  "/:id/status",
  rateLimit("user_status"),
  requireAccessToken,
  requireRole("admin"),
  asyncHandler(adminChangeStatus),
);
usersRouter.post(
  "/:alias/follow",
  rateLimit("user_follow"),
  requireAccessToken,
  asyncHandler(followUserHandler),
);
usersRouter.delete(
  "/:alias/follow",
  rateLimit("user_unfollow"),
  requireAccessToken,
  asyncHandler(unfollowUserHandler),
);
usersRouter.get(
  "/:alias/followers",
  rateLimit("user_followers"),
  asyncHandler(listFollowersHandler),
);
usersRouter.get(
  "/:alias/following",
  rateLimit("user_following"),
  asyncHandler(listFollowingHandler),
);
usersRouter.get(
  "/me/metrics",
  rateLimit("user_metrics"),
  requireAccessToken,
  asyncHandler(getMetrics),
);
usersRouter.get(
  "/:userId/metrics",
  rateLimit("user_metrics_by_id"),
  requireAccessToken,
  asyncHandler(getMetrics),
);
usersRouter.get("/:id", requireAccessToken, requireRole("admin"), asyncHandler(getById));
