name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: app_pass
          POSTGRES_DB: app_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U app_user -d app_db"
          --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Backend deps/migrate/seed
        run: |
          cd backend
          npm install
          node scripts/wait-for-db.js
          npx knex migrate:latest
          npx knex seed:run
      - name: Frontend deps/build
        run: |
          cd frontend
          npm install
          npm run build
