/**
 * Canonical route abuse-control policy.
 *
 * Values here are code-reviewed security policy, not administrator-tunable
 * application settings. Keeping them in one authority removes route-local
 * magic numbers while preserving the existing behavior.
 */
export interface RateLimitPolicy {
  points: number;
  duration: number;
}

const ROUTE_RATE_LIMIT_POLICIES = {
  "admin_reports_list": { points: 60, duration: 60 },
  "admin_reports_moderate": { points: 30, duration: 60 },
  "admin_users_action": { points: 30, duration: 60 },
  "admin_users_activate": { points: 30, duration: 60 },
  "admin_users_ban": { points: 30, duration: 60 },
  "admin_users_delete": { points: 30, duration: 60 },
  "admin_users_search": { points: 60, duration: 60 },
  "admin_users_suspend": { points: 30, duration: 60 },
  "auth_2fa_login": { points: 10, duration: 60 },
  "auth_legal_status": { points: 60, duration: 60 },
  "auth_legal_versions": { points: 60, duration: 60 },
  "auth_login": { points: 10, duration: 60 },
  "auth_logout": { points: 60, duration: 60 },
  "auth_privacy_accept": { points: 5, duration: 60 },
  "auth_privacy_revoke": { points: 5, duration: 60 },
  "auth_pw_forgot": { points: 5, duration: 60 },
  "auth_pw_reset": { points: 5, duration: 60 },
  "auth_refresh": { points: 60, duration: 60 },
  "auth_register": { points: 10, duration: 60 },
  "auth_sessions": { points: 60, duration: 60 },
  "auth_sessions_revoke": { points: 10, duration: 60 },
  "auth_terms_accept": { points: 5, duration: 60 },
  "auth_terms_revoke": { points: 5, duration: 60 },
  "auth_verify": { points: 60, duration: 60 },
  "auth_verify_resend": { points: 3, duration: 3600 },
  "badges_catalog": { points: 60, duration: 60 },
  "consent_save": { points: 10, duration: 60 },
  "consent_status": { points: 60, duration: 60 },
  "contact_get": { points: 60, duration: 60 },
  "contact_list": { points: 60, duration: 60 },
  "contact_mark_read": { points: 60, duration: 60 },
  "contact_mark_responded": { points: 60, duration: 60 },
  "contact_save_response": { points: 60, duration: 60 },
  "contact_submit": { points: 5, duration: 3600 },
  "ex_create": { points: 20, duration: 60 },
  "ex_delete": { points: 20, duration: 60 },
  "ex_get": { points: 60, duration: 60 },
  "ex_list": { points: 60, duration: 60 },
  "ex_update": { points: 20, duration: 60 },
  "feed_block_user": { points: 50, duration: 86400 },
  "feed_bookmark": { points: 100, duration: 300 },
  "feed_bookmark_list": { points: 60, duration: 60 },
  "feed_bookmark_list_user": { points: 60, duration: 60 },
  "feed_bookmark_user": { points: 100, duration: 300 },
  "feed_clone": { points: 20, duration: 60 },
  "feed_clone_user": { points: 20, duration: 60 },
  "feed_comments_create": { points: 20, duration: 3600 },
  "feed_comments_create_user": { points: 20, duration: 3600 },
  "feed_comments_delete": { points: 60, duration: 3600 },
  "feed_comments_delete_user": { points: 60, duration: 3600 },
  "feed_comments_list": { points: 120, duration: 60 },
  "feed_comments_list_user": { points: 120, duration: 60 },
  "feed_follow_user": { points: 50, duration: 86400 },
  "feed_followers_list": { points: 120, duration: 60 },
  "feed_followers_list_user": { points: 120, duration: 60 },
  "feed_following_list": { points: 120, duration: 60 },
  "feed_following_list_user": { points: 120, duration: 60 },
  "feed_leaderboard": { points: 60, duration: 60 },
  "feed_leaderboard_user": { points: 60, duration: 60 },
  "feed_like": { points: 100, duration: 300 },
  "feed_like_user": { points: 100, duration: 300 },
  "feed_link": { points: 20, duration: 60 },
  "feed_link_user": { points: 20, duration: 60 },
  "feed_public": { points: 120, duration: 60 },
  "feed_publish": { points: 20, duration: 60 },
  "feed_publish_user": { points: 20, duration: 60 },
  "feed_report_comment": { points: 20, duration: 3600 },
  "feed_report_comment_user": { points: 20, duration: 3600 },
  "feed_report_item": { points: 20, duration: 3600 },
  "feed_report_item_user": { points: 20, duration: 3600 },
  "feed_user": { points: 120, duration: 60 },
  "logs_list": { points: 60, duration: 60 },
  "logs_recent_activity": { points: 60, duration: 60 },
  "measurements_bio_create": { points: 20, duration: 60 },
  "measurements_bio_list": { points: 60, duration: 60 },
  "measurements_bio_value": { points: 30, duration: 60 },
  "measurements_bio_visibility": { points: 30, duration: 60 },
  "measurements_perf_create": { points: 20, duration: 60 },
  "measurements_perf_list": { points: 60, duration: 60 },
  "measurements_perf_value": { points: 30, duration: 60 },
  "measurements_perf_visibility": { points: 30, duration: 60 },
  "progress_exercises": { points: 60, duration: 60 },
  "progress_export": { points: 15, duration: 60 },
  "progress_plans": { points: 60, duration: 60 },
  "progress_summary": { points: 60, duration: 60 },
  "progress_trends": { points: 60, duration: 60 },
  "progress_vibes": { points: 60, duration: 60 },
  "sessions_clone": { points: 20, duration: 60 },
  "sessions_create": { points: 20, duration: 60 },
  "sessions_delete": { points: 20, duration: 60 },
  "sessions_get": { points: 60, duration: 60 },
  "sessions_list": { points: 60, duration: 60 },
  "sessions_recurrence": { points: 10, duration: 60 },
  "sessions_reopen": { points: 10, duration: 60 },
  "sessions_update": { points: 30, duration: 60 },
  "translations_bulk": { points: 10, duration: 60 },
  "translations_create": { points: 30, duration: 60 },
  "translations_delete": { points: 30, duration: 60 },
  "translations_get": { points: 100, duration: 60 },
  "translations_list": { points: 60, duration: 60 },
  "translations_metadata": { points: 30, duration: 60 },
  "translations_namespace_updates": { points: 30, duration: 60 },
  "translations_update": { points: 30, duration: 60 },
  "types_create": { points: 10, duration: 60 },
  "types_delete": { points: 10, duration: 60 },
  "types_get": { points: 60, duration: 60 },
  "types_list": { points: 60, duration: 60 },
  "types_update": { points: 10, duration: 60 },
  "user_avatar_delete": { points: 10, duration: 60 },
  "user_avatar_delete_me": { points: 10, duration: 60 },
  "user_avatar_get": { points: 60, duration: 60 },
  "user_avatar_upload": { points: 5, duration: 60 },
  "user_avatar_upload_me": { points: 5, duration: 60 },
  "user_body_progress_get": { points: 60, duration: 60 },
  "user_body_progress_photo_delete": { points: 30, duration: 60 },
  "user_body_progress_photo_get": { points: 120, duration: 60 },
  "user_body_progress_photo_upload": { points: 10, duration: 60 },
  "user_body_progress_weight": { points: 30, duration: 60 },
  "user_contacts_delete": { points: 10, duration: 300 },
  "user_contacts_email": { points: 10, duration: 300 },
  "user_contacts_get": { points: 20, duration: 60 },
  "user_contacts_phone": { points: 10, duration: 300 },
  "user_contacts_verify": { points: 10, duration: 300 },
  "user_contacts_verify_request": { points: 5, duration: 300 },
  "user_create": { points: 5, duration: 60 },
  "user_delete": { points: 10, duration: 60 },
  "user_export": { points: 2, duration: 3600 },
  "user_follow": { points: 50, duration: 86400 },
  "user_followers": { points: 120, duration: 60 },
  "user_following": { points: 120, duration: 60 },
  "user_list": { points: 10, duration: 60 },
  "user_me": { points: 60, duration: 60 },
  "user_metrics": { points: 60, duration: 60 },
  "user_metrics_by_id": { points: 60, duration: 60 },
  "user_preferences_get": { points: 60, duration: 60 },
  "user_preferences_update": { points: 20, duration: 60 },
  "user_privacy_get": { points: 60, duration: 60 },
  "user_privacy_update": { points: 20, duration: 60 },
  "user_pw": { points: 10, duration: 60 },
  "user_status": { points: 10, duration: 60 },
  "user_unfollow": { points: 50, duration: 86400 },
  "user_update": { points: 20, duration: 60 },
  "vibeforms_me_get": { points: 60, duration: 60 },
  "vibeforms_me_preferences_put": { points: 20, duration: 60 },
} satisfies Record<string, RateLimitPolicy>;

export function getRouteRateLimitPolicy(key: string): RateLimitPolicy {
  const policy = (ROUTE_RATE_LIMIT_POLICIES as Record<string, RateLimitPolicy>)[key];
  if (!policy) {
    throw new Error(`Unclassified route rate-limit policy: ${key}`);
  }
  return policy;
}
